nelmio_api_doc:
    documentation:
        info:
            title: KNB test app
            description: 'The previous 2 versions were recycled. Free the whales'
            version: 3.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
